### ISSUE TITLE
[설계 관련 문서 최종 정리] 3. UI 설계서 

### ISSUE THREAD

**Issue by JAESKAAA** [JAESKAAA/PawMap#5]
1. PPT로 문서화 작업 필요 (현재 오븐으로 초안 작업만 완료)
2. 추가적으로 수정 될 부분 있는지 검토

**Comment by help-Extinguisher** [comment]
https://ovenapp.io/view/7l6qms2Cg3VnUiP8UabQ3IpJq11Js9jL/
UI 오븐 초안 (이메일로 전송해두었음)

**Comment by JAESKAAA** [comment]
https://ovenapp.io/project/hbQpNL7BBi6xWSbg4lzbbOLm9gB9CcJz#3aBn5
UI 설계 오븐으로 대체 (최종본)
