### ISSUE TITLE
[최종점검] 1차 이슈사항

### ISSUE THREAD

**Issue by JAESKAAA** [JAESKAAA/PawMap#73]
## 1차 확인 후 이슈사항 정리

1.  <strike>사업자등록번호도 중복체크 기능 필요 (디비에도 유니크속성으로 변경필요)</strike>

2. <strike>자유게시판 글 수정에서 파일삭제했을때 테스트코드 지워야함 / 나눔게시판도 동일함</strike> 우선 완료 (안보이는부분 발견시 말해주세요)

3. <strike>게시판 글쓰기할때 자유/나눔 안나누고 해당 게시판에 바로 글 등록 되도록 가능한지 (구현X)</strike>

4. <strike>나눔게시판도 자유게시판이랑 비슷한 테마로 맞추는거 or 예정했던 카드형식으로 할지 확실히 정하기</strike> 완료!

5. <strike>나눔게시판 댓글등록시 사진깨짐 (널이라서 그런듯 / default로 사진 넣어야할 것으로 보임)</strike> 완료!

6. <strike>**(중요!!) 나눔게시판 글 삭제시 댓글 삭제 안되고있음**</strike> 완료!

7. <strike>나눔게시판에서 최초 파일 업로드시 시퀀스 2로 잡힘 (의도한것인지 확인 요망_삭제는 잘되는 것으로 보임)_
       -> boardSeq와 연결하는부분이라 그런것같습니다 이상없음 (은혜)</strike>

8. <strike>나눔게시판 nav바에서 토글이안됨 (수정완료) </strike>

9. <strike>수의사 사진 크기맞춰야함 (검색-> 병원디테일 페이지) (수정완료)</strike>

10.<strike> 채팅 라이브러리 사용법 익히기 (진행중)
* 관리자가 tawk.to 관리자페이지 로그인상태어야지 대화 가능함 (항상 들어가있어야함)
* 채팅 완료 후 작성한 이메일로 대화 내용 전송 가능
* 관리자가 접속중이 아니라면 메시지를 작성해서 보낼 수 있음 -> 해당 메시지는 관리자의 이메일로 전송됨</strike>
11. <strike>마이페이지 -> 반려동물리스트 깨짐</strike>

12. <strike>메인에 후원하기 자세히보기로 바꾸고 나눔게시판으로 넣기</strike>

13. <strike>진단서 올렸을때만 진단서확인 버튼 활성화 되도록 변경 필요</strike>

14. <strike>진단서 작성페이지 윗 부분 마진필요</strike>

15. <strike>진단서 올라가면 예약 취소 선택 안되도록 변경 필요</strike>

## <strike>추가 작업 필요</strike> (완료!)
**<strike>1. 프로젝트 readme 파일 작성하기</strike>**
  * <strike>프로젝트 개요 </strike>
  * <strike>한눈에 볼수 있도록 기능 소개 등등 필요함</strike>

**Comment by GoGyul** [comment]
2,13 완료

**Comment by help-Extinguisher** [comment]
4,5,6
7 -> board_seq로 삭제해서 그런것같습니다 일단 이상은 없습니다 (은혜)

**Comment by JAESKAAA** [comment]
리드미는 따로 작성하는것으로 하고 close 처리 하겠습니다 !

**Comment by JAESKAAA** [comment]
리드미까지 업로드 완료
